branches:
  only:
    - master
    - develop
language: ruby
rvm:
  - 1.8.7
  - 1.9.3
#  - jruby-18mode
env:
  - REDMINE_VER=1.4.5
  - REDMINE_VER=2.0.4
  - REDMINE_VER=2.1.4
  - REDMINE_VER=master
matrix:
  allow_failures:
    - env: REDMINE_VER=1.4.5
    - env: REDMINE_VER=master
    - env: REDMINE_VER=v3.3.0
  exclude: # anyone is free to adopt a build, until then, no builds that don't have a maintainer
    - rvm: 1.9.3
      env: REDMINE_VER=1.4.5
    - rvm: 1.8.7
      env: REDMINE_VER=2.1.4
    - rvm: 1.8.7
      env: REDMINE_VER=master

install: "echo skip bundle install"

script:
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_charts
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - export PATH_TO_TESTER=`pwd`/redmine_tester.sh
  - mkdir $TESTSPACE
  - cp config/database.yml.travis $TESTSPACE/database.yml
  - bash -x ./redmine_install.sh -c
  - bash -x ./redmine_install.sh -i
  - bash -x ./redmine_install.sh -t
  - bash -x ./redmine_install.sh -u

